stages:
  - main

# upload job, see https://lftp.yar.ru/lftp-man.html
main:
  stage: main
  script:
    - apt-get update -qq && apt-get install -y -qq lftp
    - lftp -c "set ftp:ssl-allow no; open -u $USER,$PASSWD $HOST; mirror -Rnev  --ignore-time --parallel=10 --exclude-glob .git --exclude .git/  "
    - cd "$CI_PROJECT_DIR/public/"
      lftp -c "set ftp:ssl-allow no; open -u $PUBLIC_USER,$PASS_USER $HOST; mirror -Rnev  --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/ "
  only:
    - main

